<a href="https://colab.research.google.com/github/Jagrav-Garg/BCS-Stack-O-Matic-Python-NumPy-and-Pandas-Exploration-Assignment/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1: Data Exploration with Pandas (30 Points)**

You will explore the California housing dataset in more detail and perform the following tasks. You can find the dataset downloaded by default in your Colab Environment in the sample_data folder:(/content/sample_data/california_housing_train.csv)

**Load the Dataset**

Load the dataset from the CSV file into a Pandas DataFrame.
Display the first 5 and last 10 rows of the data.



In [1]:
import pandas as pd

In [3]:
file_path = '/content/sample_data/california_housing_train.csv'
data = pd.read_csv(file_path)

In [4]:
first_five_rows = data.head(5)
last_ten_rows = data.tail(10)

first_five_rows, last_ten_rows

(   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0    -114.31     34.19                15.0       5612.0          1283.0   
 1    -114.47     34.40                19.0       7650.0          1901.0   
 2    -114.56     33.69                17.0        720.0           174.0   
 3    -114.57     33.64                14.0       1501.0           337.0   
 4    -114.57     33.57                20.0       1454.0           326.0   
 
    population  households  median_income  median_house_value  
 0      1015.0       472.0         1.4936             66900.0  
 1      1129.0       463.0         1.8200             80100.0  
 2       333.0       117.0         1.6509             85700.0  
 3       515.0       226.0         3.1917             73400.0  
 4       624.0       262.0         1.9250             65500.0  ,
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 16990    -124.22     41.73                28.0       3003.0           699.0 

**Data Summary**

Get a statistical summary of the dataset to examine the numerical columns.

Identify the unique values in the total_bedrooms column and determine how many distinct values it has.

```
# This is formatted as code
```



In [5]:
data_summary = data.describe()
data_summary

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [7]:
unique_bedrooms = data["total_bedrooms"].unique()
distinct_bedrooms_count = len(unique_bedrooms)
unique_bedrooms, distinct_bedrooms_count

(array([1283., 1901.,  174., ..., 1637., 1308.,  936.]), 1848)

**Data Transformation**

Add a new column to the DataFrame named total_bedrooms_per_total_rooms, calculated as total_bedrooms / total_rooms.

Compute the mean and standard deviation of the new column (total_bedrooms_per_total_rooms) and report these values.

In [8]:
data['total_bedrooms_per_total_rooms'] = data['total_bedrooms'] / data['total_rooms']
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.228617  
1                            0.248497  
2                            0.241667  
3                            0.224517  
4                            0.224209  
...                               ...  
16995                        0.177718  
16996                        0.224777  
16997                        0.198356  
16998                        0.206587  
16999                        0.164835  

[17000 rows x 10 columns]

In [9]:
mean_value = data['total_bedrooms_per_total_rooms'].mean()
std_dev_value = data['total_bedrooms_per_total_rooms'].std()

mean_value, std_dev_value

(0.21275998821034803, 0.057823008903161756)

**Data Filtering**

Filter the dataset to find rows where the median_income is greater than 5.

Create a subset of the data where the number of rooms (total_rooms) exceeds 10,000 and the median_house_value is below $150,000. Display this filtered subset.

In [10]:
filtered_data = data[data['median_income'] > 5]

In [11]:
filtered_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [12]:
subset_data = data[(data['total_rooms'] > 10000) & (data['median_house_value'] < 150000)]
subset_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

**Export Modified Data**

Save the modified DataFrame (after adding the extra column) to a new CSV file.

In [13]:
output_file_path = '/content/modified_california_housing_data.csv'
data.to_csv(output_file_path, index=False)

output_file_path

'/content/modified_california_housing_data.csv'

# **Part 2: Numerical Analysis with NumPy (30 Points)**

For this section, you will use NumPy to manipulate arrays and perform numerical operations:


**Array Creation and Indexing**

Create a 1D NumPy array of integers from 1 to 20.

Extract the even numbers from this array using slicing.

Create a 2D array with 5 rows and 4 columns, filled with random
integers between 10 and 100.

Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).

In [14]:
import numpy as np

In [15]:
array_1d = np.arange(1, 21)

In [16]:
even_numbers = array_1d[1::2]


In [17]:
array_2d = np.random.randint(10, 101, size=(5, 4))

In [18]:
subarray_2d = array_2d[:3, :2]

In [19]:
array_1d, even_numbers, array_2d, subarray_2d

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),
 array([[55, 66, 71, 82],
        [38, 76, 62, 19],
        [49, 70, 24, 25],
        [19, 75, 11, 10],
        [40, 37, 16, 77]]),
 array([[55, 66],
        [38, 76],
        [49, 70]]))

**Array Manipulation**

Reshape the 1D array of integers into a 4x5 2D array.

Flatten the 2D array back to a 1D array and print it.

Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).

In [20]:
array_1d = np.arange(1, 21)

array_2d_reshaped = array_1d.reshape(4, 5)
print("Reshaped 2D Array:")
print(array_2d_reshaped)

Reshaped 2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
array_1d_flattened = array_2d_reshaped.flatten()
print("Flattened 1D Array:")
print(array_1d_flattened)

Flattened 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [26]:
array_2d_2 = np.random.randint(1, 10, size=(5, 4))

result = np.dot(array_2d_reshaped, array_2d_2)
print(array_2d_2)
print("Matrix Multiplication Result:")
print(result)

[[8 3 6 5]
 [1 5 2 5]
 [9 5 1 6]
 [8 2 6 6]
 [9 3 9 5]]
Matrix Multiplication Result:
[[114  51  82  82]
 [289 141 202 217]
 [464 231 322 352]
 [639 321 442 487]]


**Boolean and Fancy Indexing**

Create a NumPy array of 50 random integers between 0 and 100.

Use Boolean indexing to extract all values greater than 50 from the array.

Use fancy indexing to extract elements from the array at specific indices.

In [27]:
random_array = np.random.randint(0, 101, size=50)
print("Original Array:")
print(random_array)

Original Array:
[42 95 89 33 25 42 89 36 28 70 60 69 73 94  6 45 85 26 38 38 95 89 59 18
 70 52 44  0 45 44 47 62 43 52 68 20 35 14 25 33 35 59 15 95 72 60  1 60
 55 87]


In [28]:
greater_than_50 = random_array[random_array > 50]
print("Values Greater Than 50:")
print(greater_than_50)

Values Greater Than 50:
[95 89 89 70 60 69 73 94 85 95 89 59 70 52 62 52 68 59 95 72 60 60 55 87]


In [29]:
indices = [5, 10, 20]

fancy_indexed_elements = random_array[indices]
print("Elements at Specific Indices:")
print(fancy_indexed_elements)

Elements at Specific Indices:
[42 60 95]


**Statistical Operations**

For the 2D array created earlier, calculate the mean, max, and sum along each column.

Create a mask to select elements that are greater than the mean value for each column and apply the mask to filter the array.

In [34]:
mean_values = np.mean(array_2d, axis=0)
max_values = np.max(array_2d, axis=0)
sum_values = np.sum(array_2d, axis=0)

print(array_2d)
print("Mean values column:", mean_values)
print("Max values column:", max_values)
print("Sum values column:", sum_values)

[[55 66 71 82]
 [38 76 62 19]
 [49 70 24 25]
 [19 75 11 10]
 [40 37 16 77]]
Mean values column: [40.2 64.8 36.8 42.6]
Max values column: [55 76 71 82]
Sum values column: [201 324 184 213]


In [35]:
mask = array_2d > mean_values

filtered_array = array_2d[mask]

print("Filtered Array:")
print(filtered_array)

Filtered Array:
[55 66 71 82 76 62 49 70 75 77]


# **Part 3: Problem Solving with Python Basics (20 Points)**
This part will test your understanding of basic Python operations, including control flow, loops, and error handling:


**Loops and Conditional Statements**

Print the Fibonacci sequence up to 100 using a loop.

Loop through the numbers from 1 to 50 and print:

"Fizz" for multiples of 3.

"Buzz" for multiples of 5.

"FizzBuzz" for multiples of both 3 and 5.

In [36]:
a, b = 0, 1

while a <= 100:
    print(a, end=" ")
    c=a
    a=b
    b=b+c

0 1 1 2 3 5 8 13 21 34 55 89 

In [37]:
for i in range(1, 51):
    if i%3==0 and i%5==0:
        print("FizzBuzz")
    elif i%3==0:
        print("Fizz")
    elif i%5==0:
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


**Variable-Length Arguments**

Write a solution that accepts a list of numbers and returns the median value.

Write a solution that accepts a variable number of arguments and returns the average of the numbers.

In [41]:
import statistics

def find_median(numbers):
    return statistics.median(numbers)

numbers = np.random.randint(1, 101, size=50)
median_value = find_median(numbers)
print(numbers)
print(f"Median: {median_value}")

[71  8 21 98 68 84 48 29 16 11 42  2 56 93 78 75  4  2 23 53 75 60 65 50
  5 38 67 90 97 14 77 45 91 80 93 78 43 20  4 31  1 80 14 63 55 21 48 59
 31 91]
Median: 51.5


In [42]:
average_value = np.mean(numbers)
print(f"Average: {average_value}")

Average: 49.36


**Error Handling**

Handle the case where a division by zero occurs and print an appropriate error message.

In [44]:
def divide(a, b):
    try:
        result = a/b
        return result
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
        return None

num1 = 10
num2 = 0

result = divide(num1, num2)
if result is not None:
    print(f"Result: {result}")

Error: Division by zero is not allowed.


# **Part 4: Bonus Challenge (Optional) (20 Points)**

If you’re feeling adventurous, try completing the following bonus challenge for extra credit:

**Advanced NumPy Manipulation**

Create a 3D NumPy array with specific dimensions and populate it with random numbers.

Swap two of its axes.

Perform an operation to calculate the sum of all the elements along a particular axis.

Generate a random array and use broadcasting to perform an operation that adds a vector to each row of a 2D array.

In [45]:
array_3d = np.random.randint(1, 101, size=(3, 4, 5))
print("3D Array:")
print(array_3d)

3D Array:
[[[43  5 89  3 76]
  [53 60 54 63 65]
  [31 99 64 91  8]
  [44  9 28 95 55]]

 [[98 52 45 42 62]
  [85 57  5 57 13]
  [ 3 40 97 98 29]
  [10 81  4 33 20]]

 [[20  4 64 31 81]
  [64 19 19 42 43]
  [77  8 42 99 84]
  [32 86 82 49 41]]]


In [46]:
sw_array = np.swapaxes(array_3d, 0, 1)
print("Array after swapping axes 0 and 1:")
print(sw_array)

Array after swapping axes 0 and 1:
[[[43  5 89  3 76]
  [98 52 45 42 62]
  [20  4 64 31 81]]

 [[53 60 54 63 65]
  [85 57  5 57 13]
  [64 19 19 42 43]]

 [[31 99 64 91  8]
  [ 3 40 97 98 29]
  [77  8 42 99 84]]

 [[44  9 28 95 55]
  [10 81  4 33 20]
  [32 86 82 49 41]]]


In [47]:
sw_array2 = np.swapaxes(array_3d, 0, 2)
print("Array after swapping axes 0 and 1:")
print(sw_array2)

Array after swapping axes 0 and 1:
[[[43 98 20]
  [53 85 64]
  [31  3 77]
  [44 10 32]]

 [[ 5 52  4]
  [60 57 19]
  [99 40  8]
  [ 9 81 86]]

 [[89 45 64]
  [54  5 19]
  [64 97 42]
  [28  4 82]]

 [[ 3 42 31]
  [63 57 42]
  [91 98 99]
  [95 33 49]]

 [[76 62 81]
  [65 13 43]
  [ 8 29 84]
  [55 20 41]]]


In [48]:
sum_axis_0 = np.sum(array_3d, axis=0)
print("Sum along axis 0 (layerwise):")
print(sum_axis_0)

Sum along axis 0 (layerwise):
[[161  61 198  76 219]
 [202 136  78 162 121]
 [111 147 203 288 121]
 [ 86 176 114 177 116]]


In [49]:
array_2d = np.random.randint(1, 100, size=(4, 5))
print("Original 2D Array:")
print(array_2d)

vector = np.random.randint(1, 10, size=5)
print("Vector to add to each row:")
print(vector)

result = array_2d + vector
print("Final Array:")
print(result)

Original 2D Array:
[[62 46 98 52 55]
 [33  1 82 24 16]
 [29 21 93  9 82]
 [45 77 30 49 15]]
Vector to add to each row:
[6 5 7 9 9]
Final Array:
[[ 68  51 105  61  64]
 [ 39   6  89  33  25]
 [ 35  26 100  18  91]
 [ 51  82  37  58  24]]
